[package]
name = "bitmatrix"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
opt-level = 3
debug = true
split-debuginfo = '...'  # Platform-specific.
debug-assertions = false
overflow-checks = false
lto = true
codegen-units = 1